name: WebAssembly

on:
  push:
    branches:
      - master
      - develop

  pull_request:

jobs:

  compile-esmscripten:
    name: Compile for WebAssembly
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up emscripten
      uses: mymindstorm/setup-emsdk@v11
    - name: Verify
      run: emcc -v
    - name: Get OpenSSL
      run: |
        sudo apt update
        sudo apt install cmake libssl-dev
    - name: Generate CMake files
      run: emcmake cmake -S . -B ./build
    - name: Compile
      run: cmake --build ./build -j 16 --target mo_simulator_wasm
